### ISSUE TITLE
Problems making run the EasyDemo.py

### ISSUE THREAD

**Issue by robotgradient** [mathDR/BP-AR-HMM#2]
Hi,

I am trying to run the EasyDemo.py but I am struggling with some problems.

In parameters.py, into the class ModelParams_BPHMM(), in line 79 you call to the class obsModel. Anyway, this doesnt exist.

Any suggestions??

Best wishes,

Julen Urain

**Comment by mathDR** [comment]
Hey @TheCamusean this never worked.  Sorry I abandoned this repo years ago.  I should just delete it...
